name: Tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["2.7.x", "3.4.x"] #, "3.6.x", "3.8.x", "3.9.x", "3.10.x"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install pytest && pytest tests.py
